let imgUrl=localStorage.getItem('verdeai_photo')||'',selected=localStorage.getItem('verdeai_future')||'retreat',goal=localStorage.getItem('verdeai_goal')||'retreat';
const qs=s=>document.querySelector(s), qsa=s=>[...document.querySelectorAll(s)];
const order=['discover','goals','dna','futures','studio','blueprint','tester'];
const labels=['Discover','Goals','DNA','Futures','Studio','Plan','Result'];
function image(){return imgUrl||demo}
function show(id){qsa('.view').forEach(v=>v.classList.remove('active'));document.getElementById(id).classList.add('active');const i=order.indexOf(id);if(i>=0){qs('#stepText').textContent=`Step ${i+1} of ${order.length} — ${labels[i]}`;qs('#progressBar').style.width=`${((i+1)/order.length)*100}%`}scrollTo({top:0,behavior:'smooth'})}
function next(){let cur=order.findIndex(id=>document.getElementById(id).classList.contains('active'));show(order[Math.min(cur+1,order.length-1)])}
qsa('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));qsa('[data-next]').forEach(b=>b.onclick=next);qsa('.pin').forEach(p=>p.onclick=()=>pickDiscovery(Number(p.dataset.d)));
function renderGoals(){qs('#goalCards').innerHTML=Object.entries(goals).map(([id,g])=>`<div class="goal ${id===goal?'active':''}" onclick="goal='${id}';selected='${id}';localStorage.setItem('verdeai_goal',goal);localStorage.setItem('verdeai_future',selected);render();show('futures')"><b>${g[0]}</b><strong>${g[1]}</strong></div>`).join('')}
function mini(x){return `<div class="thumb" style="background-image:url('${image()}');--tint:${x.tint};--fx:${x.fx}"><span class="overlayEl path"></span><span class="overlayEl seat"></span><span class="overlayEl tree"></span><span class="overlayEl privacy"></span><span class="overlayEl light"></span></div>`}
function card(id,x){return `<article class="card ${id===selected?'active':''}" onclick="selected='${id}';localStorage.setItem('verdeai_future',selected);render();show('studio')"><div class="cardTop" style="background:${x.color}">${x.title}<small>${x.tag}</small></div>${mini(x)}<p>${x.text}</p></article>`}
function testerText(){const f=futures[selected];return `Goal: ${goals[goal][0]}\nProperty DNA: Emerging outdoor room\nRecommended future: ${f.title}\nWhy: ${f.why}\nWeekend action: ${f.action}`}
function renderTester(){const f=futures[selected];qs('#testerCard').innerHTML=`<b>VerdeAI Beta 1.0 result</b><strong>${f.title}</strong><p><b>Goal:</b> ${goals[goal][0]}</p><p><b>Why:</b> ${f.why}</p><p><b>This week:</b> ${f.action}</p>`}
function render(){qs('#hero').style.backgroundImage=`url('${image()}')`;qs('#stage').style.backgroundImage=`url('${image()}')`;qs('#concept').style.backgroundImage=`url('${image()}')`;const f=futures[selected];qs('#concept').style.setProperty('--tint',f.tint);qs('#concept').style.setProperty('--fx',f.fx);qs('#chosenTitle').textContent=f.title;qs('#chosenText').textContent=f.text;qs('#chosenWhy').textContent=f.why;qs('#chosenAction').textContent=f.action;const first=[goal,goal==='retreat'?'wildlife':'retreat'];qs('#featured').innerHTML=first.map(id=>card(id,futures[id])).join('');qs('#futureCards').innerHTML=Object.entries(futures).map(([id,x])=>card(id,x)).join('');renderBlueprint(f);renderLayers();renderFeed();renderDNA();renderGoals();renderTester();pickDiscovery(0)}
qs('#photoInput').onchange=e=>{const f=e.target.files[0];if(!f)return;qs('#scan').classList.add('on');const r=new FileReader();r.onload=ev=>setTimeout(()=>{imgUrl=ev.target.result;try{localStorage.setItem('verdeai_photo',imgUrl)}catch(e){}qs('#scan').classList.remove('on');render();show('discover')},700);r.readAsDataURL(f)}
qs('#resetBtn').onclick=()=>{localStorage.removeItem('verdeai_photo');localStorage.removeItem('verdeai_future');localStorage.removeItem('verdeai_goal');imgUrl='';selected='retreat';goal='retreat';render();show('discover')}
qs('#againBtn').onclick=()=>show('discover');qs('#startBtn').onclick=()=>show('discover');
qs('#intensity').oninput=e=>{qs('#concept').style.setProperty('--intensity',Number(e.target.value)/100)}
function copied(){qs('#toast').classList.add('on');setTimeout(()=>qs('#toast').classList.remove('on'),1200)}
qs('#copyTesterBtn').onclick=()=>{navigator.clipboard.writeText('VerdeAI Beta 1.0\n'+testerText());copied()}
render();show('discover');