let photo=localStorage.getItem('verde_photo')||'', chosen='retreat', feedback='Not answered';
let layers={path:true,seat:true,plant:true,focus:true};
const qs=s=>document.querySelector(s), qsa=s=>[...document.querySelectorAll(s)];
function image(){return photo||demo}
function show(id){qsa('.screen').forEach(s=>s.classList.add('hidden'));qs('#'+id).classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
function start(file){if(file){const r=new FileReader();r.onload=e=>{photo=e.target.result;try{localStorage.setItem('verde_photo',photo)}catch(err){};render();scan()};r.readAsDataURL(file)}else{render();scan()}}
function scan(){show('scan');const steps=['📷 Photo received','🌿 Reading edges and open space','☀ Looking for light and shade','🚶 Checking movement and access','💡 Finding the first useful opportunity','✨ Creating three possible futures'];let i=0;qs('#scanSteps').innerHTML=steps.map(x=>`<div class="scanStep">${x}</div>`).join('');const t=setInterval(()=>{const els=qsa('.scanStep');if(els[i])els[i].classList.add('done');i++;if(i>steps.length){clearInterval(t);setTimeout(()=>show('reveal'),500)}},430)}
function card(icon,title,text){return `<div class="simpleCard"><b>${icon}</b><strong>${title}</strong><p>${text}</p></div>`}
function renderStory(){qs('#storyBody').innerHTML=`This space already feels open and adaptable. Rather than needing more plants straight away, it appears to be waiting for a stronger identity.<br><br>The biggest opportunity is deciding what role this place should play before making permanent changes.`}
function renderNoticed(){qs('#noticedGrid').innerHTML=[card('👀','Open space','There is enough flexibility to choose a clear role.'),card('🪑','Destination missing','The space needs one obvious place to pause.'),card('🌿','Edges matter','The best first move is likely near an edge, not the centre.')].join('')}
function renderDNA(){const cards=[['🏡','Personality','Blank Canvas','Open, flexible and waiting for a stronger purpose.',86],['🌳','Strongest pattern','Underused edge','The edge can become useful before the whole space changes.',91],['💡','Hidden opportunity','Create a destination','One useful place will make everything else easier.',88],['⚠','Biggest risk','Random additions','Buying things first may create clutter instead of purpose.',74]];qs('#dnaGrid').innerHTML=cards.map(x=>`<div class="dnaCard"><b>${x[0]}</b><strong>${x[1]}</strong><p>${x[2]}</p><small>${x[3]}</small><div class="score"><i style="width:${x[4]}%"></i></div></div>`).join('')}
function renderMeter(){const rows=[['Relaxation',45,82,'Create one protected sitting destination.'],['Functionality',52,88,'Give the edge a practical role.'],['Beauty',38,76,'Use one focal point before adding many plants.'],['Wildlife',41,79,'Start with a small habitat edge.'],['Flexibility',72,94,'Keep the centre adaptable.'],['Maintenance',62,84,'Improve one zone instead of the whole property.']];qs('#meterGrid').innerHTML=rows.map(x=>`<div class="simpleCard"><strong>${x[0]}</strong><p>Now: ${x[1]}% · Potential: ${x[2]}%</p><div class="score"><i style="width:${x[1]}%"></i></div><div class="score potential"><i style="width:${x[2]}%"></i></div><small>${x[3]}</small></div>`).join('')}
function renderTimeline(){qs('#timelineGrid').innerHTML=[['Now','The space is flexible but unclear.'],['This weekend','Test one destination with temporary objects.'],['One month','Keep what naturally gets used.'],['Six months','Build the anchor area properly.'],['Two years','The whole place grows around a clear purpose.'],['Future','It feels intentional, not random.']].map(x=>`<div class="simpleCard"><strong>${x[0]}</strong><p>${x[1]}</p></div>`).join('')}
function overlayHTML(){return Object.entries(layers).filter(x=>x[1]).map(([k])=>`<span class="overlay ${k}"></span>`).join('')}
function futureCard(id,f){return `<article class="futureCard" onclick="choose('${id}')"><div class="futureImage" style="background-image:url('${image()}');--tint:${f.tint};--fx:${f.fx}"><span class="overlay path"></span><span class="overlay seat"></span><span class="overlay plant"></span></div><div class="futureBody"><h3>${f.title}</h3><p>${f.short}</p><small>Confidence: ${f.confidence}%</small></div></article>`}
function renderFutures(){qs('#futureGrid').innerHTML=Object.entries(futures).map(([id,f])=>futureCard(id,f)).join('')}
function choose(id){chosen=id;renderChosen();show('detail')}
function renderChosen(){const f=futures[chosen];qs('#detailPhoto').style.backgroundImage=`url('${image()}')`;qs('#detailPhoto').style.setProperty('--tint',f.tint);qs('#detailPhoto').style.setProperty('--fx',f.fx);qs('#overlayLayer').innerHTML=overlayHTML();qs('#futureTitle').textContent=f.title;qs('#futureDescription').textContent=f.desc;qs('#futureWhy').textContent=f.why;qs('#confidenceTitle').textContent=`Confidence: ${f.confidence}%`;qs('#confidenceText').textContent=f.confidenceText;qs('#futureMeta').innerHTML=`<span>${f.difficulty}</span><span>${f.cost}</span><span>${f.time}</span>`}
function renderBudget(){const f=futures[chosen];qs('#budgetGrid').innerHTML=[['$100 test',f.budgets[0]],['$1,000 upgrade',f.budgets[1]],['$10,000 vision',f.budgets[2]]].map(x=>`<div class="simpleCard"><strong>${x[0]}</strong><p>${x[1]}</p></div>`).join('')}
function renderExperiment(){const f=futures[chosen];qs('#experimentText').innerHTML=`<strong>${f.action}</strong><br><br><span class="muted">This is a test, not a permanent decision. If it feels useful after a week, then build around it.</span>`}
function renderResult(){const f=futures[chosen];const note=qs('#feedbackNote')?qs('#feedbackNote').value.trim():'';qs('#resultPhoto').style.backgroundImage=`url('${image()}')`;qs('#resultTitle').textContent=f.title;qs('#resultLines').innerHTML=[['Property story','Open and adaptable, but waiting for a stronger identity.'],['Property personality','Blank Canvas with Practical Potential'],['Chosen future',f.title],['Confidence',f.confidence+'% — '+f.confidenceText],['Weekend experiment',f.action],['Tester feedback',feedback+(note?` — ${note}`:'')]].map(x=>`<div class="resultLine"><strong>${x[0]}</strong>${x[1]}</div>`).join('')}
function render(){['hero','scanPhoto','revealPhoto','detailPhoto','resultPhoto'].forEach(id=>qs('#'+id).style.backgroundImage=`url('${image()}')`);renderStory();renderNoticed();renderDNA();renderMeter();renderTimeline();renderFutures();renderChosen();renderBudget();renderExperiment();renderResult()}
qsa('[data-go]').forEach(b=>b.onclick=()=>{const id=b.dataset.go;if(id==='budget')renderBudget();if(id==='experiment')renderExperiment();if(id==='result')renderResult();show(id)});
qsa('.chip').forEach(b=>b.onclick=()=>{const key=b.dataset.layer;layers[key]=!layers[key];b.classList.toggle('on');renderChosen()});
qsa('.feedbackBtn').forEach(b=>b.onclick=()=>{feedback=b.dataset.feedback;qsa('.feedbackBtn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});
qs('#photoInput').onchange=e=>start(e.target.files[0]);
qs('#demoBtn').onclick=()=>start();
qs('#restartBtn').onclick=()=>{localStorage.removeItem('verde_photo');photo='';chosen='retreat';feedback='Not answered';render();show('hero')};
qs('#copyBtn').onclick=()=>{const f=futures[chosen];navigator.clipboard.writeText(`VerdeAI Tester Beta v1.23\nFuture: ${f.title}\nConfidence: ${f.confidence}%\nWeekend experiment: ${f.action}\nFeedback: ${feedback}`);qs('#toast').classList.add('on');setTimeout(()=>qs('#toast').classList.remove('on'),1200)}
qs('#testerTextBtn').onclick=()=>{navigator.clipboard.writeText('I am testing a new AI property ideas tool called VerdeAI. It takes one property photo and suggests what the space could become. Honest feedback would help a lot.');qs('#toast').classList.add('on');setTimeout(()=>qs('#toast').classList.remove('on'),1200)}
render();