const demo=`data:image/svg+xml;utf8,${encodeURIComponent(`<svg xmlns='http://www.w3.org/2000/svg' width='1500' height='950'><rect width='1500' height='950' fill='#87a96b'/><path d='M0 760 C260 600 520 625 790 500 C1070 370 1240 340 1500 270 L1500 950 L0 950Z' fill='#233c2d'/><path d='M120 900 C330 705 535 615 850 555' stroke='#ded7c8' stroke-width='88' fill='none'/><circle cx='910' cy='300' r='125' fill='#24442e'/><rect x='894' y='300' width='32' height='330' fill='#5b3f27'/><text x='70' y='105' font-size='58' fill='white' font-family='Arial' font-weight='700'>Demo property photo</text></svg>`)}`;

const goals={
  retreat:{icon:'🌿',label:'Calm retreat',personality:'Quiet Retreat with Practical Potential',story:'This space wants to slow people down. The best result will come from creating one protected spot that feels calm before adding more features.',bias:'calm, comfort and lower maintenance'},
  family:{icon:'🔥',label:'Family / friends',personality:'Gathering Place in Progress',story:'This space is asking for a clearer social role. It does not need to become fancy first; it needs one simple place where people naturally stop and gather.',bias:'people, seating and evening use'},
  maker:{icon:'🛠',label:'Workshop / useful',personality:'Maker Garden with Hidden Utility',story:'This space has practical potential. The strongest future is not only prettier planting, but a useful zone that can support making, fixing, storing or experimenting.',bias:'usefulness, storage and workflow'},
  nature:{icon:'🦋',label:'Wildlife / nature',personality:'Wildlife Edge Waiting to Happen',story:'This space could become more alive by strengthening one edge first. A small habitat pocket is a better first move than trying to redesign everything.',bias:'habitat, shade, texture and seasonal life'},
  simple:{icon:'✨',label:'Simple / low maintenance',personality:'Minimal Blank Canvas',story:'This space should stay simple. The best improvement is one strong decision, not a crowded list of features.',bias:'simplicity, ease and low maintenance'}
};

const futures={
retreat:{title:'Peaceful Retreat',short:'Quiet. Comfortable. Easy maintenance.',desc:'A calm place to sit, reset, and actually use the outdoor space.',why:'The clearest first move is creating a protected destination, not filling every empty area.',confidence:88,confidenceText:'Strong match because the space is open, flexible, and benefits from one calm anchor point.',tint:'rgba(58,111,58,.42)',fx:'radial-gradient(circle at 36% 42%,rgba(188,235,160,.35),transparent 35%)',difficulty:'Easy',cost:'Low cost',time:'Weekend',action:'Move one chair or small table into the most protected spot. Use it twice this week.',budgets:['Move a chair and add one pot or solar light.','Add a small gravel pad and two comfortable seats.','Build a defined sitting area with shade, planting and a path.']},
gather:{title:'Gathering Space',short:'Friends. Family. Evenings outside.',desc:'A simple destination for people, not just empty space.',why:'The open area can become useful fast if one social zone is marked clearly.',confidence:82,confidenceText:'Good match if the owner wants people to gather here. It needs a clear seating zone first.',tint:'rgba(168,87,22,.42)',fx:'radial-gradient(circle at 60% 60%,rgba(255,177,77,.45),transparent 28%)',difficulty:'Medium',cost:'Low–medium',time:'2 weekends',action:'Mark a temporary seating area with chairs, pots, or solar lights before building anything.',budgets:['Use existing chairs and lights to test the zone.','Add pavers, a fire bowl or a simple table.','Create an outdoor room with lighting, paving and planting.']},
maker:{title:'Maker Garden',short:'Practical. Creative. Still looks good.',desc:'A useful outdoor zone for making, fixing, storing, or experimenting without wrecking the whole yard.',why:'A practical work area can exist without turning the whole place into a storage yard.',confidence:79,confidenceText:'More experimental, but strong for practical owners who want their space to earn its keep.',tint:'rgba(55,70,82,.42)',fx:'radial-gradient(circle at 66% 62%,rgba(255,210,120,.38),transparent 32%)',difficulty:'Medium',cost:'Low–medium',time:'Weekend',action:'Clear one small work zone and mark its boundary with temporary objects before building anything permanent.',budgets:['Clear and mark one work zone.','Add a bench, storage tub or shade cover.','Create a proper workshop garden with storage, access and screening.']},
nature:{title:'Living Nature Edge',short:'Birds. Texture. Seasonal change.',desc:'A softer living edge that adds movement, wildlife and a stronger sense of place.',why:'A small habitat edge can make the whole space feel more alive without a full redesign.',confidence:84,confidenceText:'Good match when the owner wants more life and atmosphere without heavy construction.',tint:'rgba(34,120,76,.42)',fx:'radial-gradient(circle at 42% 40%,rgba(100,230,135,.35),transparent 36%)',difficulty:'Easy',cost:'Low cost',time:'Weekend',action:'Pick one edge and create a small test habitat pocket with pots, logs, mulch or native plants.',budgets:['Create a small habitat pocket with existing materials.','Add native shrubs, mulch and a bird-friendly water point.','Build a layered habitat edge with trees, shrubs and seasonal planting.']},
simple:{title:'Simple Intentional Space',short:'Clear. Easy. Not overdone.',desc:'A clean, low-maintenance direction that improves use without making the property busy.',why:'The space will improve fastest by removing uncertainty, not by adding clutter.',confidence:86,confidenceText:'Strong match for testers who want improvement without constant upkeep.',tint:'rgba(80,106,89,.38)',fx:'linear-gradient(135deg,rgba(255,255,255,.28),transparent 45%)',difficulty:'Easy',cost:'Low cost',time:'Weekend',action:'Remove one unnecessary object, mark one clean edge, and keep the centre open for a week.',budgets:['Clear clutter and define one clean edge.','Add gravel, edging or a single focal pot.','Create a simple low-maintenance layout with durable surfaces and restrained planting.']}
};