import assert from 'node:assert/strict';
import { createOneShotDryRunTransport, verifyActivationReceipt, V1046_BUILD } from '../backend/v10_4_0_secure_same_property/src/dry-run-transport-v10_4_6.mjs';

let count=0; const ok=(v,m)=>{count++;assert.equal(Boolean(v),true,m)}; const eq=(a,b,m)=>{count++;assert.equal(a,b,m)};
const envelope={contractBuild:"v10.4.0",preparationBuild:"v10.4.2",bridgeBuild:"v10.4.3",mode:"SAFE_LOCKED",selectedRecommendation:{count:1,id:"wildlife-haven",title:"Wildlife Haven"},input:{imageCount:1,image:{mimeType:"image/jpeg",byteCount:2100000,width:2048,height:1536,metadataStripped:true,orientationPreservedByBrowserDecode:true,dataRef:"single-browser-prepared-image"},clues:{}},output:{count:1,mimeType:"image/jpeg",preserveSameProperty:true,selectedFutureId:"wildlife-haven",automaticRetryCount:0},consent:{requiredAtActivation:true,collected:false,state:"pending-owner-approved-real-activation"},policy:{backendConnected:false,providerCallsEnabled:false,paidCallsLocked:true,killSwitch:true,networkAllowed:false,imageCount:1,outputCount:1,automaticRetries:0,storeInput:false,storeOutput:false}};
const config={build:'v10.4.5',configurationSource:'server-environment',environment:'server',ownerApproved:true,approvalId:'verdeai-owner-approved-2026',approvalVersion:'v10.4.5',approvalScope:'same-property-single-image-v1',backendConnected:true,providerCallsEnabled:true,paidCallsLocked:false,killSwitch:false,networkAllowed:true,providerCredentialPresent:true,providerCredentialLocation:'server-secret',transportAdapterId:'verdeai.future.transport',maxImagesPerRequest:1,maxOutputsPerRequest:1,maxPreparedImageBytes:2500000,maxEdge:2048,automaticRetries:0,storeInputImages:false,storeOutputImages:false,maxCostUsd:0.15,totalBudgetUsd:10};
const consent={collected:true,explicit:true,source:'server-verified-consent',scope:'same-property-single-image-v1',termsVersion:'v10.4.5',photoUse:'temporary-processing',outputCount:1,storeInput:false,storeOutput:false,sessionBound:true,consentId:'vda-consent-session-2026',capturedAt:'2026-08-02T00:00:00.000Z',recommendationId:'wildlife-haven'};
const fixedClock=()=>new Date('2026-08-02T00:01:00.000Z');
const transport=createOneShotDryRunTransport({clock:fixedClock});
eq(transport.used,false,'unused initially');
const receipt=transport.run({serverConfig:config,consentEvidence:consent,envelope});
eq(transport.used,true,'used after run');
eq(receipt.build,V1046_BUILD,'build');
eq(receipt.execution.simulatorCalls,1,'one call');
eq(receipt.execution.networkRequests,0,'zero network');
eq(receipt.execution.providerCalls,0,'zero provider');
eq(receipt.execution.billableEvents,0,'zero billing');
eq(receipt.execution.costUsd,0,'zero cost');
eq(receipt.execution.outputCount,0,'zero output');
eq(receipt.execution.imageCreated,false,'no image');
eq(receipt.execution.storedInputs,false,'no input storage');
eq(receipt.execution.storedOutputs,false,'no output storage');
eq(receipt.execution.automaticRetries,0,'zero retries');
ok(Object.isFrozen(receipt),'receipt frozen');ok(Object.isFrozen(receipt.gates),'gates frozen');ok(Object.isFrozen(receipt.execution),'execution frozen');
ok(verifyActivationReceipt(receipt).ok,'receipt verifies');
ok(!JSON.stringify(receipt).includes('session_1234567890'),'session redacted');ok(!JSON.stringify(receipt).includes('vda-consent-session-2026'),'consent redacted');ok(!JSON.stringify(receipt).includes('verdeai-owner-approved-2026'),'approval redacted');
let second='';try{transport.run({serverConfig:config,consentEvidence:consent,envelope})}catch(e){second=e.code}eq(second,'DRY_RUN_ALREADY_USED','second run blocked');eq(transport.receipt,receipt,'same receipt retained');
const transport2=createOneShotDryRunTransport({clock:fixedClock});
let bad='';try{transport2.run({serverConfig:{...config,ownerApproved:false},consentEvidence:consent,envelope})}catch(e){bad=e.code}ok(Boolean(bad),'invalid gate rejected');eq(transport2.used,true,'attempt consumes one shot');eq(transport2.receipt,null,'no receipt on failure');
const tampered={...receipt,execution:{...receipt.execution,networkRequests:1}};eq(verifyActivationReceipt(tampered).ok,false,'tampered receipt rejected');
console.log(`PASS ${count}/${count}: one-shot simulator, immutable redacted receipt, zero network/provider/billing/output/storage/retries.`);
