import assert from 'node:assert/strict';
import { createOneShotDryRunTransport } from '../backend/v10_4_0_secure_same_property/src/dry-run-transport-v10_4_6.mjs';
import { createReplayProofLifecycleLedger } from '../backend/v10_4_0_secure_same_property/src/lifecycle-ledger-v10_4_7.mjs';
import { createActivationReadinessAudit, verifyActivationReadinessAudit, renderOwnerReadinessReview } from '../backend/v10_4_0_secure_same_property/src/readiness-audit-v10_4_8.mjs';

let count=0; const eq=(a,b,m)=>{count++;assert.equal(a,b,m)}; const ok=(v,m)=>{count++;assert.equal(Boolean(v),true,m)};
const envelope={contractBuild:'v10.4.0',preparationBuild:'v10.4.2',bridgeBuild:'v10.4.3',mode:'SAFE_LOCKED',selectedRecommendation:{count:1,id:'wildlife-haven',title:'Wildlife Haven'},input:{imageCount:1,image:{mimeType:'image/jpeg',byteCount:2100000,width:2048,height:1536,metadataStripped:true,orientationPreservedByBrowserDecode:true,dataRef:'single-browser-prepared-image'},clues:{}},output:{count:1,mimeType:'image/jpeg',preserveSameProperty:true,selectedFutureId:'wildlife-haven',automaticRetryCount:0},consent:{requiredAtActivation:true,collected:false,state:'pending-owner-approved-real-activation'},policy:{backendConnected:false,providerCallsEnabled:false,paidCallsLocked:true,killSwitch:true,networkAllowed:false,imageCount:1,outputCount:1,automaticRetries:0,storeInput:false,storeOutput:false}};
const config={build:'v10.4.5',configurationSource:'server-environment',environment:'server',ownerApproved:true,approvalId:'verdeai-owner-approved-2026',approvalVersion:'v10.4.5',approvalScope:'same-property-single-image-v1',backendConnected:true,providerCallsEnabled:true,paidCallsLocked:false,killSwitch:false,networkAllowed:true,providerCredentialPresent:true,providerCredentialLocation:'server-secret',transportAdapterId:'verdeai.future.transport',maxImagesPerRequest:1,maxOutputsPerRequest:1,maxPreparedImageBytes:2500000,maxEdge:2048,automaticRetries:0,storeInputImages:false,storeOutputImages:false,maxCostUsd:0.15,totalBudgetUsd:10};
const consent={collected:true,explicit:true,source:'server-verified-consent',scope:'same-property-single-image-v1',termsVersion:'v10.4.5',photoUse:'temporary-processing',outputCount:1,storeInput:false,storeOutput:false,sessionBound:true,consentId:'vda-consent-session-2026',capturedAt:'2026-08-02T00:00:00.000Z',recommendationId:'wildlife-haven'};
const receipt=createOneShotDryRunTransport({clock:()=>new Date('2026-08-02T00:01:00.000Z')}).run({serverConfig:config,consentEvidence:consent,envelope});
const ledger=createReplayProofLifecycleLedger({clock:()=>new Date('2026-08-02T00:02:00.000Z')});
ledger.acceptReceipt(receipt); ledger.transition(receipt.receiptId,'audited'); ledger.transition(receipt.receiptId,'closed');
const snapshot=ledger.snapshot();
const audit=createActivationReadinessAudit(snapshot,{clock:()=>new Date('2026-08-02T00:05:00.000Z')});
eq(audit.currentState,'SAFE_LOCKED','safe locked'); eq(audit.readyForRealCalls,false,'calls locked'); eq(audit.proof.networkRequests,0,'network zero'); eq(audit.proof.billableEvents,0,'billable zero'); eq(audit.recordedGuardrails.maxCostUsdPerRequest,0.15,'cost cap recorded'); eq(audit.recordedGuardrails.totalPilotBudgetUsd,10,'budget recorded'); eq(audit.ownerDecisionsRequired.length,8,'owner decisions'); ok(Object.isFrozen(audit),'audit frozen'); ok(verifyActivationReadinessAudit(audit).ok,'audit verifies');
const review=renderOwnerReadinessReview(audit); ok(review.includes('DO NOT ACTIVATE') || review.includes('Do not activate'),'review blocks activation'); ok(review.includes('Network requests: 0'),'review proof'); ok(!review.includes('vda-consent-session-2026'),'consent id absent');
let incomplete=''; const ledger2=createReplayProofLifecycleLedger(); ledger2.acceptReceipt(receipt); try{createActivationReadinessAudit(ledger2.snapshot())}catch(e){incomplete=e.code} eq(incomplete,'INCOMPLETE_LIFECYCLE','incomplete blocked');
const tampered={...audit,activationAuthorised:true}; eq(verifyActivationReadinessAudit(tampered).ok,false,'tampered activation rejected');
console.log(`PASS ${count}/${count}: readiness audit is immutable, redacted, zero-side-effect, and blocks activation.`);
