window.VERDEAI_CONFIG = {
  version: "9.8.5.1",
  apiBaseUrl: "",
  useBackend: false,
  staticMode: true,
  ownerApprovals: { provider: true, backendHost: true, pilotBudget: true, testerLimit: true, retentionPolicy: true },
  pilotApproved: false,
  provider: "none",
  backendHost: "not-connected",
  pilotBudgetTotalUsd: 0,
  providerReservationCapUsd: 0,
  maxCostPerRenderUsd: 0,
  invitedTesterLimit: 0,
  perSessionLimit: 0,
  perIpDailyLimit: 0,
  retentionPolicy: "browser-only",
  mockMode: true,
  killSwitch: true,
  providerCallsEnabled: false,
  paidCallsLocked: true,
  frontendApiKeyPresent: false,
  activationRequires: ["A future owner decision after Results State Reset Hotfix v9.8.5.1 passes physical desktop and Android testing"]
};
