import { estimateRenderCost, providerLabel } from "./costs.js";
import { renderWithMock } from "./adapters/mockProvider.js";
import { renderWithReplicateFlux } from "./adapters/replicateFlux.js";
import { renderWithOpenAIImage } from "./adapters/openaiImage.js";
import { renderWithStabilityAI } from "./adapters/stabilityAI.js";

const PROVIDER_ADAPTERS = {
  mock: renderWithMock,
  "replicate-flux": renderWithReplicateFlux,
  "openai-image": renderWithOpenAIImage,
  "stability-ai": renderWithStabilityAI
};

export function renderProvidersStatus() {
  const realEnabled = process.env.VERDEAI_REAL_RENDERING_ENABLED === "true";
  return [
    { id: "mock", label: "Mock / concept board fallback", enabled: true, paid: false, keyRequired: false },
    { id: "replicate-flux", label: "Replicate / FLUX", enabled: realEnabled && Boolean(process.env.REPLICATE_API_TOKEN), paid: true, keyRequired: true },
    { id: "openai-image", label: "OpenAI image generation", enabled: realEnabled && Boolean(process.env.OPENAI_API_KEY), paid: true, keyRequired: true },
    { id: "stability-ai", label: "Stability AI", enabled: realEnabled && Boolean(process.env.STABILITY_API_KEY), paid: true, keyRequired: true }
  ];
}

export function validateRenderRequest(body = {}) {
  const provider = body.provider || "mock";
  const count = Math.max(1, Math.min(Number(body.count || body.requestedCount || 1), 6));
  const estimatedCostUsd = estimateRenderCost(provider, count);
  const maxCostUsd = Number(body.maxCostUsd ?? 0);
  const confirmCost = body.confirmCost === true;
  const realProviderRequested = provider !== "mock";
  const realRenderingEnabled = process.env.VERDEAI_REAL_RENDERING_ENABLED === "true";

  return {
    provider,
    count,
    futureId: body.futureId || "belonging",
    prompt: body.prompt || "Prompt generated by VerdeAI render prompt builder.",
    imageReference: body.imageReference || "browser-local-photo-or-demo",
    selectedFuture: body.selectedFuture || body.futureTitle || "Belonging Garden",
    estimatedCostUsd,
    maxCostUsd,
    confirmCost,
    realProviderRequested,
    realRenderingEnabled,
    allowed: !realProviderRequested || (realRenderingEnabled && confirmCost && maxCostUsd >= estimatedCostUsd),
    blockReason: !realProviderRequested ? "mock-provider" : !realRenderingEnabled ? "real-rendering-disabled" : !confirmCost ? "cost-not-confirmed" : maxCostUsd < estimatedCostUsd ? "max-cost-too-low" : "none"
  };
}

export async function handleRenderRequest(body = {}) {
  const request = validateRenderRequest(body);
  const adapter = PROVIDER_ADAPTERS[request.provider] || renderWithMock;

  if (request.provider !== "mock" && !request.allowed) {
    const fallback = await renderWithMock(request);
    return {
      ok: true,
      mode: "safe-render-blocked",
      provider: request.provider,
      providerLabel: providerLabel(request.provider),
      message: "Paid rendering is intentionally blocked. Returning mock fallback until backend provider keys and cost confirmation are configured.",
      blockReason: request.blockReason,
      confirmationRequired: true,
      estimatedCostUsd: request.estimatedCostUsd,
      maxCostUsd: request.maxCostUsd,
      mockFallback: fallback
    };
  }

  const result = await adapter(request);
  return {
    ok: true,
    mode: request.provider === "mock" ? "mock-render" : "provider-render-scaffold",
    provider: request.provider,
    providerLabel: providerLabel(request.provider),
    futureId: request.futureId,
    selectedFuture: request.selectedFuture,
    requestedCount: request.count,
    estimatedCostUsd: request.estimatedCostUsd,
    confirmationRequired: request.provider !== "mock",
    prompt: request.prompt,
    result
  };
}
