import { readFileSync, existsSync } from "node:fs";

const required = [
  "index.html",
  "styles/main.css",
  "js/app.js",
  "config.js",
  "CHANGELOG.md",
  "BUILD_STATUS.md",
  "backend/server.js",
  "api/openapi-alpha.json",
  "api/render-contract.v6.0.json",
  "backend/render/renderService.js",
  "backend/render/adapters/mockProvider.js"
];

const missing = required.filter((file) => !existsSync(file));
if (missing.length) {
  console.error("Missing required files:", missing.join(", "));
  process.exit(1);
}

const html = readFileSync("index.html", "utf8");
const js = readFileSync("js/app.js", "utf8");
const css = readFileSync("styles/main.css", "utf8");

const checks = [
  [html.includes("photoInput"), "photo input exists"],
  [html.includes("testerPage"), "public tester page exists"],
  [html.includes("testerPageVisual"), "tester visual stage exists"],
  [html.includes("futureGrid"), "future grid exists"],
  [html.includes("constraintSelect"), "main problem selector exists"],
  [html.includes("quickStartStatus"), "quick tester checklist exists"],
  [html.includes("starterSuggestions"), "starter suggestions container exists"],
  [html.includes("under-building"), "under-building situation option exists"],
  [html.includes("shade-dark"), "shade/dark problem option exists"],
  [js.includes("runAnalysis"), "analysis function exists"],
  [js.includes("localStorage"), "local save support exists"],
  [js.includes("overlayHtml"), "overlay engine exists"],
  [js.includes("plantPictureOverlayHtml"), "plant picture overlay engine exists"],
  [js.includes("renderTesterPage"), "tester page render logic exists"],
  [js.includes("specificityReasons"), "specificity reasoning exists"],
  [js.includes("STARTER_PRESETS"), "starter preset logic exists"],
  [js.includes("visibleSiteLanguage"), "visible-site language exists"],
  [js.includes("captureAnalysisSnapshot"), "analysis snapshot capture exists"],
  [js.includes("restoreAnalysisSnapshot"), "analysis snapshot restore exists"],
  [js.includes("cleanPropertyNote"), "property note cleanup exists"],
  [js.includes("compressImageFile"), "client-side image compression exists"],
  [js.includes("copyShareCode"), "share code export exists"],
  [js.includes("importShareCode"), "share code import exists"],
  [js.includes("testerInviteText"), "tester invite copy exists"],
  [js.includes("readinessScore"), "beta readiness scoring exists"],
  [html.includes("publicBetaChecklist"), "public beta checklist exists"],
  [html.includes("copyTesterInviteBtn"), "tester invite button exists"],
  [html.includes("handoffStatus"), "handoff status exists"],
  [html.includes("smartNextCard"), "smart next card exists"],
  [js.includes("smartNextPlan"), "smart next plan logic exists"],
  [js.includes("handleSmartNextAction"), "smart next button logic exists"],
  [js.includes("restoreCurrentSession"), "autosave session restore exists"],
  [js.includes("persistCurrentSessionNow"), "autosave session persist exists"],
  [html.includes("sessionRecovery"), "session recovery card exists"],
  [html.includes("Run shaded garden self-test"), "self-test button exists"],
  [js.includes("runShadedGardenSelfTest"), "self-test runner exists"],
  [js.includes("saveSelfTestProject"), "self-test saved project exists"],
  [js.includes("shadedSelfTestImage"), "self-test image exists"],
  [css.includes(".self-test-card"), "self-test card CSS exists"],
  [css.includes(".tester-page-shell"), "tester page CSS exists"],
  [css.includes(".plant-picture-layer"), "plant overlay CSS exists"],
  [css.includes(".session-recovery-card"), "session recovery CSS exists"],
  [css.includes(".smart-next-card"), "smart next card CSS exists"],
  [html.includes("Copy Share Code"), "share code button exists"],
  [html.includes("analysis stays locked"), "design tab stability copy exists"],
  [css.includes(".stability-note"), "stability note CSS exists"],
  [css.includes(".beta-test-card"), "public beta handoff CSS exists"],
  [css.includes(".readiness-meter"), "beta readiness meter CSS exists"],
  [css.includes(".quick-start-card"), "quick start CSS exists"],
  [css.includes(".clue-coach"), "clue coach CSS exists"],
  [css.includes("@media"), "responsive CSS exists"],
  [css.includes(":focus-visible"), "accessibility focus styles exist"],
  [js.includes('const BUILD_VERSION = "8.7"') && js.includes('version: BUILD_VERSION'), "v8.7 app version exists"],
  [js.includes("selected-status-pill"), "selected future status exists"],
  [js.includes("result-summary-answer"), "first move result callout exists"],
  [css.includes("v8.7 multi-scenario credibility + tester handoff"), "v8.7 scenario and handoff CSS exists"],

  [html.includes("Build v8.7"), "visible v8.7 build label exists"],
  [html.includes("Concept Board · Not AI Render"), "concept trust label exists"],
  [js.includes("dashboard-overlay-key"), "dashboard overlay key exists"],
  [js.includes("photo-concept-layer"), "distinct photo concept layer exists"],
  [js.includes("Recommended · Selected"), "combined recommended and selected state exists"],
  [!js.includes("state.selectedFutureId = snap.selectedFutureId"), "future selection is not reset by analysis snapshot"],
  [css.includes(".future-quick-tags"), "compact mobile future tags exist"],
  [js.includes("SCENARIO_GUIDES"), "scenario-specific guides exist"],
  [js.includes("SCENARIO_FUTURE_BOOSTS"), "scenario ranking boosts exist"],
  [js.includes("recommendedFutureId"), "recommendation state is independent"],
  [js.includes("function recommendedFuture"), "recommended future helper exists"],
  [js.includes("Mostly blank / open"), "blank-canvas starter clue exists"],
  [js.includes("Workshop / storage area"), "workshop starter clue exists"],
  [html.includes("data-feedback-reaction=\"useful\""), "one-tap feedback exists"],
  [js.includes("saveQuickFeedback"), "one-tap feedback logic exists"],
  [js.includes("VERDEAI87:"), "v8.7 share code prefix exists"],
  [html.includes("feedbackReviewSummary"), "local feedback review summary exists"],
  [html.includes("feedbackReactionFilter"), "feedback reaction filter exists"],
  [html.includes("feedbackSituationFilter"), "feedback situation filter exists"],
  [html.includes("feedbackBuildFilter"), "feedback build filter exists"],
  [html.includes("feedbackDisagreementSummary"), "recommendation disagreement summary exists"],
  [html.includes("feedbackEvidenceInsight"), "evidence insight exists"],
  [html.includes("feedbackCsvInput"), "feedback CSV import exists"],
  [js.includes("feedbackDisagreementStats"), "recommendation disagreement logic exists"],
  [js.includes("evidenceInsight"), "evidence threshold logic exists"],
  [js.includes("importFeedbackCsvFile"), "feedback CSV import logic exists"],
  [js.includes("parseCsvRows"), "CSV parser exists"],
  [js.includes("state.version = BUILD_VERSION"), "restored projects use current build version"],
  [js.includes("Selected different from recommendation"), "CSV contains disagreement column"],

  [html.includes("feedbackEvidenceFilter"), "feedback evidence filter exists"],
  [html.includes("feedbackEvidenceBoundary"), "genuine tester evidence boundary exists"],
  [html.includes("feedbackNoteThemes"), "repeated tester wording area exists"],
  [html.includes("data-feedback-evidence-kind"), "tester/internal feedback source control exists"],
  [html.includes("data-feedback-issue-stage"), "optional issue area control exists"],
  [js.includes("testerEvidenceItems"), "tester-only trend boundary exists"],
  [js.includes("repeatedTesterNoteLanguage"), "repeated tester wording logic exists"],
  [js.includes("Evidence type"), "CSV exports evidence type"],
  [js.includes("Issue area"), "CSV exports issue area"],
  [html.includes("feedbackReviewList"), "local feedback review list exists"],
  [js.includes("normaliseFeedbackItem"), "feedback migration exists"],
  [js.includes("renderFeedbackReview"), "feedback review renderer exists"],
  [js.includes("buildVersion"), "feedback stores build version"],
  [js.includes("propertySituation"), "feedback stores property situation"],
  [js.includes("selectedFuture"), "feedback stores selected future"],
  [js.includes("optionalNote"), "feedback stores optional note"],
  [html.includes("Private in this static beta"), "plain-English privacy wording exists"],
  [html.includes("appStatus"), "screen-reader status region exists"],
  [js.includes("prepareAccessibility"), "accessibility setup exists"],
  [css.includes("prefers-contrast:more"), "increased contrast support exists"],

  [html.includes("Property Futures Dashboard"), "property futures dashboard exists"],
  [html.includes("dashboardFutureCards"), "dashboard future cards container exists"],
  [html.includes("dashboardCompass"), "dashboard compass exists"],
  [html.includes("dashboardEvolution"), "dashboard evolution strip exists"],
  [html.includes("dashboardCopyBtn"), "dashboard copy button exists"],
  [html.includes("dashboardCopyTopBtn"), "top dashboard copy button exists"],
  [js.includes("dashboardFutureCardHtml"), "dashboard future card renderer exists"],
  [js.includes("dashboardFutureTag"), "future-specific dashboard tags exist"],
  [js.includes("futureSceneIntent"), "future design intent renderer exists"],
  [js.includes("propertyMovieSteps"), "property movie steps exist"],
  [js.includes("cleanTesterResultText"), "clean dashboard result copy exists"],
  [css.includes(".dashboard-futures-grid"), "dashboard futures CSS exists"],
  [css.includes(".compass-ring"), "property compass score rings CSS exists"],
  [html.includes("AI Render Setup"), "AI render setup screen exists"],
  [html.includes("renderProviderSelect"), "render provider selector exists"],
  [html.includes("Render Prompt Builder"), "render prompt builder exists"],
  [html.includes("renderSelectedFutureBtn"), "render selected future button exists"],
  [html.includes("renderFutureSelect"), "render future selector exists"],
  [html.includes("oneFutureRenderPreview"), "one future render preview exists"],
  [js.includes("renderOneFuturePreview"), "one future preview renderer exists"],
  [js.includes("futurePromptEmphasis"), "future-specific prompt emphasis exists"],
  [js.includes("buildRenderPrompts"), "render prompt builder logic exists"],
  [js.includes("RENDER_PROVIDER_COSTS"), "render provider cost estimates exist"],
  [js.includes("mockRenderFutures"), "mock render flow exists"],
  [css.includes(".render-prompt-card"), "render prompt card CSS exists"],
];

const failed = checks.filter(([ok]) => !ok);
if (failed.length) {
  failed.forEach(([, label]) => console.error("Failed:", label));
  process.exit(1);
}

console.log("VerdeAI v8.7 smoke test passed.");
